apiVersion: v1
kind: Namespace
metadata:
  name: cnasg
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cnasg-custom-operator
  namespace: cnasg
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cnasg-custom-operator
subjects:
- kind: ServiceAccount
  name: cnasg-custom-operator
  namespace: cnasg
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cnasg-custom-operator
  namespace: cnasg
spec:
  selector:
    matchLabels:
      app: cnasg-custom-operator
  replicas: 1
  template:
    metadata:
      labels:
        app: cnasg-custom-operator
    spec:
      serviceAccountName: cnasg-custom-operator
      containers:
      - image: djsoon/cnasg-custom-operator
        name: cnasg-custom-operator
        imagePullPolicy: Always
