apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dex-user-role
rules:
  - apiGroups:
      - ""
      - apps
      - autoscaling
      - batch
      - extensions
      - networking.k8s.io
      - policy
      - rbac.authorization.k8s.io
      - storage.k8s.io
    resources:
      - componentstatuses
      - configmaps
      - cronjobs
      - daemonsets
      - deployments
      - events
      - endpoints
      - horizontalpodautoscalers
      - ingress
      - ingresses
      - jobs
      - limitranges
      - namespaces
      - nodes
      - pods
      - pods/log
      - pods/exec
      - persistentvolumes
      - persistentvolumeclaims
      - resourcequotas
      - replicasets
      - replicationcontrollers
      - secrets
      - serviceaccounts
      - services
      - statefulsets
      - storageclasses
      - clusterroles
      - roles
    verbs:
      - get
      - watch
      - list
      - create
      - delete
      - patch
  - nonResourceURLs:
      - '*'
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create